---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
library(ggplot2)
library(dplyr)
```


```{r}
setwd("C:/Users/denni/Onedrive/Desktop/Bioinformatics Work/BBp53n scRNAseq/August_2025_Analysis/")

diffExp <- read.csv("diffExp_limma OPCLIKEvsEverthing_samples.csv", header = TRUE)


diffExp$diffexpressed <- "NS"
diffExp$diffexpressed[diffExp$logFC > 1.0 & diffExp$adj.P.Val <= 0.001] <- "UPREGULATED"
diffExp$diffexpressed[diffExp$logFC < -1.0 & diffExp$adj.P.Val <= 0.001] <- "DOWNREGULATED"

nrow(dplyr::filter(diffExp, diffexpressed == "UPREGULATED"))
nrow(dplyr::filter(diffExp, diffexpressed == "DOWNREGULATED"))

highlight_label_df <- diffExp %>%
    filter(X %in% c("Myc", "Cd44", "Tnc", "Adam12", "Cdk1", "Top2a", "Tgfb1", "Olig2", "Itgb8", "Sox2", "Erbb4", "Cdkn2a"))

```


```{r}
library(ggplot2)
library(ggrepel)

ggplot(data = diffExp, aes(x = logFC, y = -log10(adj.P.Val), col = diffexpressed)) + 
  scale_colour_manual(values = c("#93D4FF", "grey", "#A10300")) +
  geom_point(size = 3) +
  geom_point(data = highlight_label_df, aes(x = logFC, y = -log10(adj.P.Val)), size = 5, color = "black") +
  geom_label_repel(data = highlight_label_df, aes(label = X), color = "black", box.padding = 1, 
                  point.padding = 0.5, segment.color = 'black', size = 5) +
  geom_vline(xintercept=c(-1, 1), col="black", alpha = 0.5, size = 1, linetype = "twodash") +
  geom_hline(yintercept = -log10(0.01), col = "black", alpha = 0.5, size = 1, linetype = "twodash") +
  #xlim(c(-4, 4)) +
  #ylim(c(0,10)) + 
  theme(legend.position = "none", 
        text=element_text(size=20), 
        panel.background = element_blank(),
        panel.grid.major = element_blank(),
        axis.line = element_line(color = "black"))
```

```{r}
library(pals)
glasbey()
c([1] "#0000FF" "#FF0000" "#00FF00" "#000033" "#FF00B6" "#005300" "#FFD300" "#009FFF" "#9A4D42" "#00FFBE" "#783FC1" "#1F9698"
[13] "#FFACFD" "#B1CC71" "#F1085C" "#FE8F42" "#DD00FF" "#201A01" "#720055" "#766C95" "#02AD24" "#C8FF00" "#886C00" "#FFB79F"
[25] "#858567" "#A10300" "#14F9FF" "#00479E" "#DC5E93" "#93D4FF" "#004CFF" "#F2F318")

highlight_label_df <- diffExp %>%
    filter(X %in% c("Myc", "Cd44", "Tnc", "Adam12", "Cdk1", "Top2a", "Tgfb1", "Olig2", "Itgb8", "Sox2", "Erbb4", "Cdkn2a"))

ggplot(data = diffExp, aes(x = logFC, y = -log10(adj.P.Val), col = diffexpressed)) + 
  scale_colour_manual(values = c("grey", "lightgrey", "#93D4FF")) +
  geom_point(size = 3) +
  geom_point(data = highlight_label_df, aes(x = logFC, y = -log10(adj.P.Val)), size = 5, color = "black") +
  geom_label_repel(data = highlight_label_df, aes(label = X), color = "black", box.padding = 1, 
                  point.padding = 0.5, segment.color = 'black', size = 5) +
  geom_vline(xintercept=c(-1, 1), col="black", alpha = 0.5, size = 1, linetype = "twodash") +
  geom_hline(yintercept = -log10(0.01), col = "black", alpha = 0.5, size = 1, linetype = "twodash") +
  #xlim(c(-4, 4)) +
  #ylim(c(0,10)) + 
  theme(legend.position = "none", 
        text=element_text(size=20), 
        panel.background = element_blank(),
        panel.grid.major = element_blank(),
        axis.line = element_line(color = "black"))

```




